name: Deploy API to Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
    tags-ignore:
      - '*'
    # Only run if the commit message contains the word 'deploy'
    types: [created, deleted, pushed]

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 --push --tag vladigpasev/archtag-api:latest .

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key ${USER}@${HOST} << 'EOF'
            cd /path/to/your/project
            docker-compose pull archtag-api
            docker-compose up -d archtag-api
          EOF
