name: Deploy API to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create application.properties file
        run: |
          mkdir -p src/main/resources
          cat > src/main/resources/application.properties <<EOL
          spring.application.name=security

          # Updated Database Configuration
          spring.datasource.url=${{ secrets.DB_URL }}
          spring.datasource.username=${{ secrets.DB_USERNAME }}
          spring.datasource.password=${{ secrets.DB_PASSWORD }}
          spring.datasource.driver-class-name=org.postgresql.Driver

          spring.jpa.hibernate.ddl-auto=update
          spring.jpa.show-sql=false
          spring.jpa.properties.hibernate.format_sql=true
          spring.jpa.database=postgresql
          spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

          authentication.secret-key=${{ secrets.AUTH_SECRET_KEY }}
          authentication.token-expiration=60

          # PERFORMANCE SETTINGS
          server.tomcat.max-threads=3
          spring.threads.virtual.enabled=true

          # Email Configuration
          spring.mail.host=smtp.office365.com
          spring.mail.port=587
          spring.mail.username=${{ secrets.EMAIL_USERNAME }}
          spring.mail.password=${{ secrets.EMAIL_PASSWORD }}
          spring.mail.properties.mail.smtp.auth=true
          spring.mail.properties.mail.smtp.starttls.enable=true

          # Set the maximum file size (e.g., 10MB)
          spring.servlet.multipart.max-file-size=10MB
          # Set the maximum request size (e.g., 10MB)
          spring.servlet.multipart.max-request-size=10MB

          webapp.url=https://app.archtag.org
          storage.location=/usr/share/nginx/html/storage

          # Stripe Configuration
          stripe.apiKey=${{ secrets.STRIPE_API_KEY }}
          stripe.success.url=${{ secrets.STRIPE_SUCCESS_URL }}
          stripe.cancel.url=${{ secrets.STRIPE_CANCEL_URL }}
          EOL

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/archtag-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/archtag-api:latest

  deploy:
    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key ${USER}@${HOST} << 'EOF'
            echo "Connecting to server"
            cd ~/archtag
            echo "Pulling new Docker images"
            docker-compose pull archtag-api
            echo "Bringing up the updated containers with force recreate"
            docker-compose up -d --force-recreate archtag-api
            echo "Deployment complete"
          EOF
